# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Keychron settings
  boot.extraModprobeConfig = ''
  options hid_apple fnmode=0
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bdb744ce-6fc4-4191-88ab-124e4031fca8";
      fsType = "btrfs";
      options = [ "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B46-E3EF";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
